source "https://rubygems.org"
gem "jekyll", "~> 4.0.0"
gem "just-the-docs"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

